SELECT
    id                                      AS case_id,
    NULLIF(type, '')                        AS variation_type_name,
    NULL                                    AS variation_type_id,
    NULL                                    AS employee_id,
    NULLIF(title, '')                       AS description,
    NULLIF(sender, '')                      AS sender,
    NULLIF(receiver, '')                    AS receiver,
    NULLIF(status, '')                      AS status,
    NULLIF(duedate, '')                     AS deadline,
    NULLIF(createdby, '')                   AS created_by,
    NULLIF(projectid, '')                   AS ext_project_id,
    NULLIF(casenumber, '')                  AS name,
    createddate::timestamp                  AS variation_date,
    EXTRACT(YEAR FROM createddate::date)    AS year,
    EXTRACT(MONTH FROM createddate::date)   AS month_number,
    TO_CHAR(createddate::date, 'Month')     AS created_month_name,
    NULLIF(modifieddate, '')                AS modified_date,
    NULL                                    AS date_closed,
    COALESCE(totalamount, 0)                AS total_amount,
    COALESCE(acceptedamount, 0)             AS accepted_amount,
    COALESCE(declinedamount, 0)             AS declined_amount,
    COALESCE(nothandledamount, 0)           AS not_handled_amount,
    dbt_scd_id,
    dbt_updated_at,
    dbt_valid_from,
    dbt_valid_to
FROM {{ ref('endringer_case_snapshot') }}
WHERE dbt_valid_to IS NULL
