SELECT
    id,
    qty,
    NULLIF(date, '')                           AS date,
    locked,
    NULLIF(userid, '')                         AS user_id,
    approved,
    NULLIF(companyid, '')                      AS company_id,
    NULLIF(createdat, '')                      AS created_at,
    isdeleted                                  AS is_deleted,
    manualqty                                  AS manual_qty,
    NULLIF(projectid, '')                      AS project_id,
    NULLIF(starttime, '')                      AS start_time,
    companyids                                 AS company_ids,
    NULLIF(modifiedat, '')                     AS modified_at,
    recversion                                 AS rec_version,
    NULLIF(absencetypeid, '')                  AS absence_type_id,
    NULLIF(approvedbyname, '')                 AS approved_by_name,
    NULLIF(employeenumber, '')                 AS employee_number,
    NULLIF(lockeddatetime, '')                 AS locked_date_time,
    NULLIF(registrationid, '')                 AS registration_id,
    NULLIF(absencetypecode, '')                AS absence_type_code,
    NULLIF(absencetypename, '')                AS absence_type_name,
    NULLIF(createdbyuserid, '')                AS created_by_user_id,
    payrollapproved                            AS payroll_approved,
    NULLIF(approveddatetime, '')               AS approved_date_time,
    NULLIF(modifiedbyuserid, '')               AS modified_by_user_id,
    NULLIF(modifieddatetime, '')               AS modified_date_time,
    NULLIF(payrollsummaryid, '')               AS payroll_summary_id,
    NULLIF(projectcompanyid, '')               AS project_company_id,
    ispayrollexportabsence                     AS is_payroll_export_absence,
    NULLIF(payrollapproveddatetime, '')        AS payroll_approved_date_time,
    registrationsickleavereason                AS registration_sick_leave_reason,
    NULLIF(registrationbirthdateofchild, '')   AS registration_birth_date_of_child
FROM
    {{ source('raw_nrc_source', 'source_ditio_absence_registrations') }}
