SELECT
    id::VARCHAR                                       AS application_id,
    job_id::TEXT                                      AS job_id,
    status_id::TEXT                                   AS status_id,
    ref                                               AS ref,
    email                                             AS email,
    gclid                                             AS gclid,
    source                                            AS source,
    status                                            AS status,
    ab_test                                           AS ab_test,
    utm_term                                          AS utm_term,
    last_name                                         AS last_name,
    dt_created::TIMESTAMP                             AS created_at,
    first_name                                        AS first_name,
    utm_medium                                        AS utm_medium,
    utm_source                                        AS utm_source,
    agency_name                                       AS agency_name,
    dt_modified::TIMESTAMP                            AS modified_at,
    source_type                                       AS source_type,
    uploaded_by                                       AS uploaded_by,
    utm_content                                       AS utm_content,
    status_group::TEXT                                AS status_group,
    utm_campaign                                      AS utm_campaign,
    rating_average::NUMERIC                           AS rating_average,
    recommender_name                                  AS recommender_name,
    rejection_reason                                  AS rejection_reason,
    application_owner                                 AS application_owner,
    original_referrer                                 AS original_referrer,
    recommender_email                                 AS recommender_email,
    (rejection_communicated::TEXT)::BOOLEAN           AS rejection_communicated,
    dbt_scd_id,
    dbt_updated_at,
    dbt_valid_from,
    dbt_valid_to
FROM {{ ref('jobylon_application_snapshot') }}
WHERE dbt_valid_to IS NULL
