SELECT
    {{ dbt_utils.generate_surrogate_key(['"external_id"']) }}      AS work_order_id,
    2                                                              AS tenant_id,
    'Gunnar Knutsen'                                               AS tenant_name,
    6                                                              AS data_source_id,
    'Admmit'                                                       AS data_source_name,
    project_name,
    customer_name,
    external_id,
    receipt_customer,
    created_at,
    created_by,
    unnamed_6,
    price_offer,
    significant_project,
    any_project_affiliation,
    index_yes_no,
    base_index_qqyyyy,
    which_index,
    index_start_qqyyyy,
    comment,
    responsible_controller,
    responsible_operating_charger,
    date_reviewed,
    comment_1,
    project_number,
    employee_id_controller,
    employee_id_driftlsleder
FROM {{ ref('stg__admmit_potential_project') }}
