SELECT 
    time_record_sk,
    record_id,
    time_type_id,
    time_type,
    hours,
    date,
    year,
    month,
    month_name,
    employee_id,
    project_id,
    company_id,
    company_name,
    division_id,
    division_name,
    department_id,
    department_name,
    data_source_name,
    created_date_time,
    modified_date_time,
    CASE WHEN time_type = 'Ordinary Hours' THEN TRUE ELSE FALSE END AS is_ordinary_hours,
    CASE WHEN time_type = 'Overtime Hours' THEN TRUE ELSE FALSE END AS is_overtime,
    CASE WHEN time_type IN ('Ubehandlet fravær', 'Sykemelding (korttids)', 'Sykemelding (langtids)', 'Egenmelding') THEN TRUE ELSE FALSE END AS is_sick_leave
FROM {{ ref('int_get_gk_time_records') }}