name: 'dbt_test'
version: '1.0.0'
config-version: 2

profile: 'dbt_test'

model-paths: ["models"]
snapshot-paths: ["snapshots"]
seed-paths: ["seeds"]

models:
  dbt_test:
    staging:
      +materialized: table
      +schema: staging
      
    intermediate:
      +materialized: table
      +schema: intermediate

    marts:
      +materialized: table
      +schema: marts

    reports:
      +materialized: table
      +schema: reporting

snapshots:
  dbt_test:
    +target_schema: snapshots

seeds:
      +schema: seeds