dbt_test:
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('APPBASE_DB_HOST') }}"
      user: "{{ env_var('APPBASE_DB_USER') }}"
      password: "{{ env_var('APPBASE_DB_PASSWORD') }}"
      port: "{{ env_var('APPBASE_DB_PORT') | int }}"
      dbname: "{{ env_var('APPBASE_DB_NAME') }}"
      schema: public
      threads: 6
  target: dev