SELECT
    internalid          AS internal_id,
    externalid          AS external_id,
    clientid            AS client_id,
    nationalityid       AS nationality_id,
    departmentid        AS department_id,
    managerid           AS manager_id,
    supplierid          AS supplier_id,
    dailyrateid         AS daily_rate_id,
    shifttypeid         AS shift_type_id,
    languageid          AS language_id,
    employmenttypeid    AS employment_type_id,
    employeeabsenceid   AS employee_absence_id,
    salarytypeid        AS salary_type_id,
    sex                 AS gender,
    city                AS city,
    name                AS name,
    address             AS address,
    zipcode             AS zip_code,
    isactive            AS is_active,
    language            AS language,
    sizeshoe            AS size_shoe,
    createdon           AS created_on,
    dailyrate           AS daily_rate,
    isdeleted           AS is_deleted,
    otherinfo           AS other_info,
    paidbreak           AS paid_break,
    sizepants           AS size_pants,
    modifiedon          AS modified_on,
    salarytype          AS salary_type,
    sizejacket          AS size_jacket,
    cardnophone         AS card_no_phone,
    certificate         AS certificate,
    dateofbirth         AS date_of_birth,
    description         AS description,
    managername         AS manager_name,
    nationality         AS nationality,
    weeklyhours         AS weekly_hours,
    employeddate        AS employed_date,
    hourlydriver        AS hourly_driver,
    worklocation        AS work_location,
    departmentname      AS department_name,
    educertificate      AS edu_certificate,
    employmenttype      AS employment_type,
    hseqcardnumber      AS hseq_card_number,
    endofemployment     AS end_of_employment,
    supplierremarks     AS supplier_remarks,
    accesscardnumber    AS access_card_number,
    hideindeviations    AS hide_in_deviations,
    bringsvehiclehome   AS brings_vehicle_home,
    workingpercentage   AS working_percentage,
    nextwageadjustment  AS next_wage_adjustment,
    privatephonenumber  AS private_phone_number,
    tenureatemployment  AS tenure_at_employment,
    onlyshowownvehicles AS only_show_own_vehicles,
    dbt_scd_id,
    dbt_updated_at,
    dbt_valid_from,
    dbt_valid_to
FROM {{ ref('admmit_employee_snapshot') }}
WHERE dbt_valid_to IS NULL
