SELECT
    customerid                    AS customer_id,
    projectid                     AS project_id,
    employeeid                    AS employee_id,
    internalid                    AS internal_id,
    vehicleid                     AS vehicle_id,
    hangerid                      AS hanger_id,
    clientid                      AS client_id,
    orderid                       AS order_id,
    leaderid                      AS leader_id,
    statusid                      AS status_id,
    invoiceid                     AS invoice_id,
    customerreceiptid             AS customer_receipt_id,
    foremanreceiptid              AS foreman_receipt_id,
    customerlocationid            AS customer_location_id,
    responsibleemployeesignedid   AS responsible_employee_signed_id,
    customersignatureattachmentid AS customer_signature_attachment_id,
    date                          AS date,
    description                   AS description,
    orderno                       AS order_no,
    timefrom                      AS time_from,
    timeto                        AS time_to,
    isdeleted                     AS is_deleted,
    createdon                     AS created_on,
    modifiedon                    AS modified_on,
    phone                         AS phone,
    ourref                        AS our_ref,
    price1                        AS price1,
    price2                        AS price2,
    price3                        AS price3,
    yourref                       AS your_ref,
    invoiced                      AS invoiced,
    ordertype                     AS order_type,
    hangername                    AS hanger_name,
    statusname                    AS status_name,
    agreedprice                   AS agreed_price,
    contactinfo                   AS contact_info,
    invoicedate                   AS invoice_date,
    projectname                   AS project_name,
    vehiclename                   AS vehicle_name,
    customername                  AS customer_name,
    employeename                  AS employee_name,
    formrecipient                 AS form_recipient,
    invoicestatus                 AS invoice_status,
    customersigned                AS customer_signed,
    receiptaddress                AS receipt_address,
    supplierstatus                AS supplier_status,
    customerorderno               AS customer_order_no,
    customerreceipt               AS customer_receipt,
    invoiceisdeleted              AS invoiceis_deleted,
    driverdescription             AS driver_description,
    employeefinalized             AS employee_finalized,
    messageforemployee            AS message_for_employee,
    supplierstatusdate            AS supplier_status_date,
    customerlocationname          AS customer_location_name,
    driverdescriptioncustomer     AS driver_description_customer,
    responsibleemployeesigned     AS responsible_employee_signed,
    customerattachmentfilename    AS customer_attachment_filename,
    customerreceiptattachments    AS customer_receipt_attachments,
    suppliercommentforcustomer    AS supplier_comment_for_customer,
    responsibleemployeesignedname AS responsible_employee_signed_name,
    dbt_scd_id,
    dbt_updated_at,
    dbt_valid_from,
    dbt_valid_to
FROM {{ ref('admmit_work_order_snapshot') }}
WHERE dbt_valid_to IS NULL
