SELECT
    "Project name"                        AS project_name,
    "Customer"                            AS customer_name,
    "External ID"                         AS external_id,
    "Receipt customer"                    AS receipt_customer,
    "Created"                             AS created_at,
    "Created by"                          AS created_by,
    "Unnamed: 6"                          AS unnamed_6,
    "Price offer"                         AS price_offer,
    "Significant project"                 AS significant_project,
    "Any project affiliation"             AS any_project_affiliation,
    "Index (Yes/No)"                      AS index_yes_no,
    "Base index (QQYYYY)"                 AS base_index_qqyyyy,
    "Which index"                         AS which_index,
    "When does the index start? (QQYYYY)" AS index_start_qqyyyy,
    "Comment"                             AS comment,
    "Responsible controller"              AS responsible_controller,
    "Responsible operating charger"       AS responsible_operating_charger,
    "Date reviewed"                       AS date_reviewed,
    "Comment.1"                           AS comment_1,
    "Project number"                      AS project_number,
    "Employee id controller"              AS employee_id_controller,
    "Employee id driftlsleder"            AS employee_id_driftlsleder,
    dbt_scd_id,
    dbt_updated_at,
    dbt_valid_from,
    dbt_valid_to
FROM {{ ref('admmit_potential_project_snapshot') }}
WHERE dbt_valid_to IS NULL
