SELECT
    "Id"                           AS id,
    "ResponsibleEmployeeId"        AS responsible_employee_id,
    "Name"                         AS name,
    "Description"                  AS description,
    "ContactPerson"                AS contact_person,
    "Address"                      AS address,
    "ZipCode"                      AS zip_code,
    "City"                         AS city,
    "PhoneNo"                      AS phone_no,
    "Email"                        AS email,
    "Web"                          AS web,
    "ExternalId"                   AS external_id,
    "ClientId"                     AS client_id,
    "CreatedOn"                    AS created_on,
    "CreatedBy"                    AS created_by,
    "ModifiedOn"                   AS modified_on,
    "ModifiedBy"                   AS modified_by,
    "IsDeleted"                    AS is_deleted,
    "CustomerGroupId"              AS customer_group_id,
    "Comment"                      AS comment,
    "WorkOrderReceipt"             AS work_order_receipt,
    "YourRef"                      AS your_ref,
    "DefaultOrderConfirmationText" AS default_order_confirmation_text,
    "UserName"                     AS user_name,
    "PasswordHash"                 AS password_hash,
    "LastLogin"                    AS last_login,
    "InvoiceTerms"                 AS invoice_terms,
    "InvoiceEmail"                 AS invoice_email,
    "UseInTimesheet"               AS use_in_timesheet,
    "DoNotUse"                     AS do_not_use,
    "DoNotUseReason"               AS do_not_use_reason,
    "OrganizationNumber"           AS organization_number,
    "InvoicingNotes"               AS invoicing_notes,
    "DepartmentId"                 AS department_id
FROM {{ ref('gk_azure_blob_customers_snapshot') }}
WHERE dbt_valid_to IS NULL AND "IsDeleted" = FALSE