SELECT
    "Id"                     AS id,
    "WorkOrderId"            AS work_order_id,
    "Number"                 AS number,
    "VehicleId"              AS vehicle_id,
    "HangerId"               AS hanger_id,
    "EmployeeId"             AS employee_id,
    "LoadPlaceId"            AS load_place_id,
    "LoadReceiptNo"          AS load_receipt_no,
    "LoadInvoiced"           AS load_invoiced,
    "UnloadPlaceId"          AS unload_place_id,
    "UnloadReceiptNo"        AS unload_receipt_no,
    "KmStart"                AS km_start,
    "KmStop"                 AS km_stop,
    "KmTotal"                AS km_total,
    "TimeStart"              AS time_start,
    "TimeStop"               AS time_stop,
    "TimeTotal"              AS time_total,
    "TimeBreak"              AS time_break,
    "ClientId"               AS client_id,
    "CreatedOn"              AS created_on,
    "CreatedBy"              AS created_by,
    "ModifiedOn"             AS modified_on,
    "ModifiedBy"             AS modified_by,
    "IsDeleted"              AS is_deleted,
    "Comment"                AS comment,
    "IsBreak"                AS is_break,
    "VatId"                  AS vat_id,
    "AccountId"              AS account_id,
    "ItemId"                 AS item_id,
    "Price"                  AS price,
    "Discount"               AS discount,
    "Total"                  AS total,
    "VehicleOwnerId"         AS vehicle_owner_id,
    "VehicleOwnerPercentage" AS vehicle_owner_percentage,
    "VehicleOwnerTotal"      AS vehicle_owner_total,
    "VehicleOwnerComment"    AS vehicle_owner_comment,
    "Quantity"               AS quantity,
    "NonInvoicable"          AS non_invoicable,
    "NonSettleable"          AS non_settleable,
    "WeighingId"             AS weighing_id,
    "LoadPlaceFreeText"      AS load_place_free_text,
    "UnloadPlaceFreeText"    AS unload_place_free_text,
    "ItemVehicleTypeId"      AS item_vehicle_type_id,
    "ApprovedDateLeader"     AS approved_date_leader,
    "ApprovedByLeader"       AS approved_by_leader,
    "IsExpense"              AS is_expense,
    "WeighingNo"             AS weighing_no,
    "EstPrice"               AS est_price,
    "EstSettle"              AS est_settle,
    "NoPrice"                AS no_price,
    "EstCost"                AS est_cost,
    "EstExpense"             AS est_expense,
    "Text1"                  AS text1,
    "Text2"                  AS text2,
    dbt_scd_id,
    dbt_updated_at,
    dbt_valid_from,
    dbt_valid_to
FROM {{ ref('gk_azure_blob_work_order_items_snapshot') }}
WHERE dbt_valid_to IS NULL
