SELECT
    projectnumber         AS project_number,
    internalid            AS internal_id,
    externalid            AS external_id,
    clientid              AS client_id,
    departmentid::VARCHAR AS department_id,
    managerid             AS manager_id,
    customerid            AS customer_id,
    locationid            AS location_id,
    description           AS description,
    tripprice             AS trip_price,
    hourprice             AS hour_price,
    triphours             AS trip_hours,
    numofdiets            AS no_of_diets,
    triphoursavailability AS trip_hours_availability,
    hoursselectroutebyday AS hours_select_route_by_day,
    plannedstartdate      AS planned_start_date,
    plannedenddate        AS planned_end_date,
    actualstartdate       AS actual_start_date,
    actualenddate         AS actual_end_date,
    active                AS is_active,
    foremanreceiptemail   AS foreman_receipt_email,
    customerreceiptemail  AS customer_receipt_email,
    invoiceemail          AS invoice_email,
    usepricematrix        AS use_price_matrix,
    customerrefno         AS customer_ref_no,
    customername          AS customer_name,
    createdon             AS created_on,
    modifiedon            AS modified_on,
    isdeleted             AS is_deleted,
    dbt_scd_id,
    dbt_updated_at,
    dbt_valid_from,
    dbt_valid_to
FROM {{ ref('admmit_project_snapshot') }}
WHERE dbt_valid_to IS NULL