SELECT
    "Id"                    AS id,
    "ProjectNumber"         AS project_number,
    "ExternalId"            AS external_id,
    "ClientId"              AS client_id,
    "DepartmentId"          AS department_id,
    "ManagerId"             AS manager_id,
    "CustomerId"            AS customer_id,
    "LocationId"            AS location_id,
    "Description"           AS description,
    "ForemanReceiptEmail"   AS foreman_receipt_email,
    "CustomerReceiptEmail"  AS customer_receipt_email,
    "InvoiceEmail"          AS invoice_email,
    "UsePriceMatrix"        AS use_price_matrix,
    "CustomerRefNo"         AS customer_ref_no,
    "CreatedOn"             AS created_on,
    "CreatedBy"             AS created_by,
    "ModifiedOn"            AS modified_on,
    "ModifiedBy"            AS modified_by,
    "IsDeleted"             AS is_deleted,
    "TripPrice"             AS trip_price,
    "HourPrice"             AS hour_price,
    "TripHours"             AS trip_hours,
    "NumOfDiets"            AS num_of_diets,
    "TripHoursAvailability" AS trip_hours_availability,
    "HoursSelectRouteByDay" AS hours_select_route_by_day,
    "PlannedStartDate"      AS planned_start_date,
    "PlannedEndDate"        AS planned_end_date,
    "ActualStartDate"       AS actual_start_date,
    "ActualEndDate"         AS actual_end_date,
    "Active"                AS active,
    "Notes"                 AS notes,
    "ExternalId2"           AS external_id_2,
    "ContactPerson"         AS contact_person,
    "PhoneNo"               AS phone_no,
    "HideInTripPlanner"     AS hide_in_trip_planner,
    "DisableDrivercardHrs" AS disable_drivercard_hrs,
    dbt_scd_id,
    dbt_updated_at,
    dbt_valid_from,
    dbt_valid_to
FROM {{ ref('gk_azure_blob_projects_snapshot') }}
WHERE dbt_valid_to IS NULL