SELECT
    "Id"                            AS id,
    "ResponsibleEmployeeSignedId"   AS responsible_employee_signed_id,
    "EmployeeId"                    AS employee_id,
    "Date"                          AS work_order_date,
    "Invoiced"                      AS invoiced,
    "Description"                   AS description,
    "VehicleId"                     AS vehicle_id,
    "HangerId"                      AS hanger_id,
    "ClientId"                      AS client_id,
    "CreatedOn"                     AS created_on,
    "CreatedBy"                     AS created_by,
    "ModifiedOn"                    AS modified_on,
    "ModifiedBy"                    AS modified_by,
    "IsDeleted"                     AS is_deleted,
    "ResponsibleEmployeeSigned"     AS responsible_employee_signed,
    "ForemanReceiptId"              AS foreman_receipt_id,
    "CustomerReceiptId"             AS customer_receipt_id,
    "InvoiceId"                     AS invoice_id,
    "OrderNo"                       AS order_no,
    "CustomerOrderNo"               AS customer_order_no,
    "CustomerId"                    AS customer_id,
    "OurRef"                        AS our_ref,
    "YourRef"                       AS your_ref,
    "LeaderId"                      AS leader_id,
    "MessageForEmployee"            AS message_for_employee,
    "StatusId"                      AS status_id,
    "ProjectId"                     AS project_id,
    "OrderType"                     AS order_type,
    "OrderId"                       AS order_id,
    "CustomerLocationId"            AS customer_location_id,
    "CustomerSignatureAttachmentId" AS customer_signature_attachment_id,
    "DriverDescription"             AS driver_description,
    "CustomerSigned"                AS customer_signed,
    "CustomerReceiptAttachments"    AS customer_receipt_attachments,
    "TimeFrom"                      AS time_from,
    "TimeTo"                        AS time_to,
    "Txt1"                          AS txt1,
    "Txt2"                          AS txt2,
    "Txt3"                          AS txt3,
    "Price1"                        AS price1,
    "Price2"                        AS price2,
    "Price3"                        AS price3,
    "ContactInfo"                   AS contact_info,
    "Phone"                         AS phone,
    "ReceiptAddress"                AS receipt_address,
    "DriverDescriptionCustomer"     AS driver_description_customer,
    "AgreedPrice"                   AS agreed_price,
    "SupplierId"                    AS supplier_id,
    "SupplierStatus"                AS supplier_status,
    "SupplierStatusDate"            AS supplier_status_date,
    "SupplierCommentForCustomer"    AS supplier_comment_for_customer,
    "EmployeeFinalized"             AS employee_finalized,
    "ItemVehicleTypeId"             AS item_vehicle_type_id,
    "ConfirmedDate"                 AS confirmed_date,
    "ConfirmedById"                 AS confirmed_by_id,
    "TripNo"                        AS trip_no,
    "Assignment"                    AS assignment,
    "Temp1"                         AS temp1,
    "Temp2"                         AS temp2,
    "StartedDate"                   AS started_date,
    "StartedById"                   AS started_by_id,
    lastupdated,
    dbt_scd_id,
    dbt_updated_at,
    dbt_valid_from,
    dbt_valid_to
FROM {{ ref('gk_azure_blob_work_orders_snapshot') }}
WHERE dbt_valid_to IS NULL
