SELECT
    id::INTEGER                            AS id,
    NULLIF(TRIM(description), '')          AS description,
    novat::BOOL                            AS is_no_vat,
    NULLIF(TRIM(title), '')                AS title,
    locked::BOOL                           AS is_locked,
    NULLIF(TRIM(ourref), '')               AS our_ref,
    NULLIF(changed, '')::TIMESTAMP         AS last_modified_at,
    NULLIF(created, '')::TIMESTAMP         AS created_at,
    NULLIF(duedate, '')::TIMESTAMP         AS due_date,
    NULLIF(TRIM(billterms), '')            AS bill_terms,
    NULLIF(TRIM(edistatus), '')            AS edi_status,
    invoiceno::INTEGER                     AS invoice_no,
    netamount::NUMERIC                     AS net_amount,
    projectid::INTEGER                     AS project_id,
    NULLIF(TRIM(projectno), '')::INTEGER   AS project_no,
    vatamount::NUMERIC                     AS vat_amount,
    NULLIF(TRIM(contractno), '')           AS contract_no,
    creditnote::BOOL                       AS is_credit_note,
    customerid::INTEGER                    AS customer_id,
    hidecodeno::BOOL                       AS is_hide_code_no,
    hidemarkup::BOOL                       AS is_hide_markup,
    NULLIF(ledgerdate, '')::TIMESTAMP      AS ledger_date,
    vatinvoice::BOOL                       AS is_vat_invoice,
    NULLIF(TRIM(changedname), '')          AS changed_name,
    NULLIF(TRIM(createdname), '')          AS created_name,
    NULLIF(TRIM(customerref), '')          AS customer_ref,
    NULLIF(invoicedate, '')::TIMESTAMP     AS invoice_date,
    NULLIF(TRIM(billaddress1), '')         AS bill_address_1,
    NULLIF(TRIM(billaddress2), '')         AS bill_address_2,
    NULLIF(TRIM(billaddress3), '')         AS bill_address_3,
    NULLIF(TRIM(billaddress4), '')         AS bill_address_4,
    NULLIF(TRIM(billaddress5), '')         AS bill_address_5,
    NULLIF(TRIM(billaddress6), '')         AS bill_address_6,
    NULLIF(TRIM(customername), '')         AS customer_name,
    NULLIF(TRIM(customerref2), '')         AS customer_ref_2,
    NULLIF(TRIM(extinvoiceno), '')         AS ext_invoice_no,
    NULLIF(TRIM(billtermscode), '')        AS bill_terms_code,
    billtermsdays::NUMERIC                 AS bill_terms_days,
    changeduserid::INTEGER                 AS changed_user_id,
    contractorvat::BOOL                    AS is_contractor_vat,
    createduserid::INTEGER                 AS created_user_id,
    NULLIF(TRIM(customervatno), '')        AS customer_vat_no,
    invoiceamount::NUMERIC                 AS invoice_amount,
    NULLIF(TRIM(invoicenumber), '')        AS invoice_number,
    invoicetypeid::INTEGER                 AS invoice_type_id,
    totalworkcost::NUMERIC                 AS total_work_cost,
    customeramount::NUMERIC                AS customer_amount,
    lockedtosource::BOOL                   AS is_locked_to_source,
    taxreductionid::INTEGER                AS tax_reduction_id,
    creditinvoiceid::INTEGER               AS credit_invoice_id,
    NULLIF(TRIM(invoicetypename), '')      AS invoice_type_name,
    readyforinvoice::BOOL                  AS is_ready_for_invoice,
    NULLIF(TRIM(customertypename), '')     AS customer_type_name,
    customercontactid::INTEGER             AS customer_contact_id,
    invoicestatuscode::INTEGER             AS invoice_status_code,
    NULLIF(TRIM(invoicestatusname), '')    AS invoice_status_name,
    originalnetamount::NUMERIC             AS original_net_amount,
    taxreductionamount::NUMERIC            AS tax_reduction_amount,
    NULLIF(TRIM(customercontactname), '')  AS customer_contact_name,
    dbt_scd_id,
    dbt_updated_at,
    dbt_valid_from,
    dbt_valid_to
FROM {{ ref('next_erp_customer_invoices_snapshot') }}
WHERE dbt_valid_to IS NULL

