SELECT
    id::INTEGER                            AS id,
    NULLIF(TRIM(description), '')          AS description,
    NULLIF(TRIM(name), '')                 AS name,
    closed::BOOL                           AS is_closed,
    NULLIF(changed, '')::TIMESTAMP         AS last_modified_at,
    NULLIF(created, '')::TIMESTAMP         AS created_at,
    NULLIF(TRIM(district), '')             AS district,
    reminder::BOOL                         AS is_reminder,
    NULLIF(TRIM(salaryno), '')             AS salary_no,
    statusid::INTEGER                      AS status_id,
    foremanid::INTEGER                     AS foreman_id,
    NULLIF(orderdate, '')::TIMESTAMP       AS order_date,
    projectid::INTEGER                     AS project_id,
    creditrisk::BOOL                       AS is_credit_risk,
    customerid::INTEGER                    AS customer_id,
    NULLIF(TRIM(reportsign), '')           AS report_sign,
    signonsite::BOOL                       AS is_sign_on_site,
    statuscode::INTEGER                    AS status_code,
    NULLIF(TRIM(statusname), '')           AS status_name,
    NULLIF(TRIM(changedname), '')          AS changed_name,
    NULLIF(TRIM(createdname), '')          AS created_name,
    NULLIF(TRIM(foremanname), '')          AS foreman_name,
    hasdocument::BOOL                      AS has_document,
    pricetypeid::INTEGER                   AS price_type_id,
    NULLIF(TRIM(projectname), '')          AS project_name,
    workorderno::INTEGER                   AS work_order_no,
    NULLIF(TRIM(customername), '')         AS customer_name,
    servicemanid::INTEGER                  AS service_man_id,
    changeduserid::INTEGER                 AS changed_user_id,
    contractorvat::BOOL                    AS is_contractor_vat,
    createduserid::INTEGER                 AS created_user_id,
    earnedrevenue::NUMERIC                 AS earned_revenue,
    fullyinvoiced::BOOL                    AS is_fully_invoiced,
    NULLIF(productionend, '')::TIMESTAMP   AS production_end,
    NULLIF(TRIM(projectnumber), '')        AS project_number,
    totalworkcost::NUMERIC                 AS total_work_cost,
    calculatedcost::NUMERIC                AS calculated_cost,
    includeonoffer::BOOL                   AS is_include_on_offer,
    NULLIF(TRIM(servicemanname), '')       AS service_man_name,
    bookedcosttotal::NUMERIC               AS booked_cost_total,
    NULLIF(productionstart, '')::TIMESTAMP AS production_start,
    workpoolgroupid::INTEGER               AS work_pool_group_id,
    bookedhourstotal::NUMERIC              AS booked_hours_total,
    budgethourstotal::NUMERIC              AS budget_hours_total,
    NULLIF(TRIM(customertypename), '')     AS customer_type_name,
    totalworkrevenue::NUMERIC              AS total_work_revenue,
    calculatedrevenue::NUMERIC             AS calculated_revenue,
    customercontactid::INTEGER             AS customer_contact_id,
    NULLIF(TRIM(customerreference), '')    AS customer_reference,
    bookedrevenuetotal::NUMERIC            AS booked_revenue_total,
    contributionmargin::NUMERIC            AS contribution_margin,
    NULLIF(TRIM(customercontactname), '')  AS customer_contact_name,
    totalearnednotinvoiced::NUMERIC        AS total_earned_not_invoiced,
    contributionmarginpercent::NUMERIC     AS contribution_margin_percent,
    dbt_scd_id,
    dbt_updated_at,
    dbt_valid_from,
    dbt_valid_to
FROM {{ ref('next_erp_work_order_snapshot') }}
WHERE dbt_valid_to IS NULL

