SELECT
    id::INTEGER                                    AS id,
    NULLIF(created, '')::TIMESTAMP                 AS created_at,
    createduserid::INTEGER                         AS created_user_id,
    NULLIF(changed, '')::TIMESTAMP                 AS last_modified_at,
    changeduserid::INTEGER                         AS changed_user_id,
    NULLIF(TRIM(projectno), '')::INTEGER           AS project_no,
    NULLIF(TRIM(projectname), '')                  AS project_name,
    NULLIF(TRIM(projecttypename), '')              AS project_type_name,
    NULLIF(TRIM(costcentername), '')               AS cost_center_name,
    NULLIF(TRIM(projectresourcegroupname), '')     AS project_resource_group_name,
    NULLIF(TRIM(pricetypename), '')                AS price_type_name,
    NULLIF(TRIM(tagfield1name), '')                AS tag_field_1_name,
    NULLIF(TRIM(tagfield2name), '')                AS tag_field_2_name,
    projectmanagerid::INTEGER                      AS project_manager_id,
    NULLIF(TRIM(projectmanagername), '')           AS project_manager_name,
    workleaderid::INTEGER                          AS work_leader_id,
    NULLIF(TRIM(workleadername), '')               AS work_leader_name,
    NULLIF(projectstart, '')::TIMESTAMP            AS project_start,
    NULLIF(projectend, '')::TIMESTAMP              AS project_end,
    NULLIF(TRIM(workplaceid), '')                  AS workplace_id,
    NULLIF(TRIM(customername), '')                 AS customer_name,
    NULLIF(TRIM(customertypename), '')             AS customer_type_name,
    projectstatusid::INTEGER                       AS project_status_id,
    NULLIF(TRIM(projectstatusname), '')            AS project_status_name,
    projectstatuscode::INTEGER                     AS project_status_code,
    budgetcost::NUMERIC                            AS budget_cost,
    budgetrevenue::NUMERIC                         AS budget_revenue,
    bookedhours::NUMERIC                           AS booked_hours,
    bookedawohours::NUMERIC                        AS booked_awo_hours,
    slpcost::NUMERIC                               AS slp_cost,
    slprevenue::NUMERIC                            AS slp_revenue,
    contributionmarginamountslp::NUMERIC           AS contribution_margin_amount_slp,
    contributionmarginpercentslp::NUMERIC          AS contribution_margin_percent_slp,
    NULLIF(TRIM(forecast), '')                     AS forecast,
    NULLIF(forecastperioddate, '')::TIMESTAMP      AS forecast_period_date,
    bookedcost::NUMERIC                            AS booked_cost,
    bookedrevenue::NUMERIC                         AS booked_revenue,
    bookedawocost::NUMERIC                         AS booked_awo_cost,
    bookedaworevenue::NUMERIC                      AS booked_awo_revenue,
    budgethours::NUMERIC                           AS budget_hours,
    forecasthours::NUMERIC                         AS forecast_hours,
    workordercost::NUMERIC                         AS work_order_cost,
    workorderrevenue::NUMERIC                      AS work_order_revenue,
    contributionmarginamount::NUMERIC              AS contribution_margin_amount,
    contributionmarginpercent::NUMERIC             AS contribution_margin_percent,
    contributionmarginwo::NUMERIC                  AS contribution_margin_wo,
    contributionmarginwopercent::NUMERIC           AS contribution_margin_wo_percent,
    earnedrevenue::NUMERIC                         AS earned_revenue,
    earnedrevenuenotinvoiced::NUMERIC              AS earned_revenue_not_invoiced,
    invoiceable::NUMERIC                           AS invoiceable,
    currentcontributionmargin::NUMERIC             AS current_contribution_margin,
    budgetcontributionmarginpercent::NUMERIC       AS budget_contribution_margin_percent,
    budgetcontributionmarginamount::NUMERIC        AS budget_contribution_margin_amount,
    paymentplanamount::NUMERIC                     AS payment_plan_amount,
    paymentplanwithheldamount::NUMERIC             AS payment_plan_withheld_amount,
    paymentplanoutcome::NUMERIC                    AS payment_plan_outcome,
    NULLIF(finalinspectiondate, '')::TIMESTAMP     AS final_inspection_date,
    NULLIF(guaranteeinspectiondate, '')::TIMESTAMP AS guarantee_inspection_date,
    guaranteetime::NUMERIC                         AS guarantee_time,
    dbt_scd_id,
    dbt_updated_at,
    dbt_valid_from,
    dbt_valid_to
FROM {{ ref('next_erp_project_snapshot') }}
WHERE dbt_valid_to IS NULL

