SELECT
    id::INTEGER                            AS id,
    NULLIF(date, '')::TIMESTAMP            AS date,
    debit::BOOL                            AS is_debit,
    hours::NUMERIC                         AS hours,
    locked::BOOL                           AS is_locked,
    userid::INTEGER                        AS user_id,
    NULLIF(changed, '')::TIMESTAMP         AS last_modified_at,
    NULLIF(created, '')::TIMESTAMP         AS created_at,
    addition::BOOL                         AS is_addition,
    approved::BOOL                         AS is_approved,
    attested::BOOL                         AS is_attested,
    costunit::NUMERIC                      AS cost_unit,
    NULLIF(TRIM(fullname), '')             AS full_name,
    invoiced::BOOL                         AS is_invoiced,
    NULLIF(stoptime, '')::TIME             AS stop_time,
    breaktime::NUMERIC                     AS break_time,
    NULLIF(TRIM(diarynote), '')            AS diary_note,
    isabsence::BOOL                        AS is_absence,
    piecework::BOOL                        AS is_piecework,
    priceunit::NUMERIC                     AS price_unit,
    projectid::INTEGER                     AS project_id,
    NULLIF(TRIM(projectno), '')::INTEGER   AS project_no,
    NULLIF(starttime, '')::TIME            AS start_time,
    totalcost::NUMERIC                     AS total_cost,
    NULLIF(attesttime, '')::TIMESTAMP      AS attest_time,
    customerid::INTEGER                    AS customer_id,
    NULLIF(TRIM(employeeno), '')::INTEGER  AS employee_no,
    NULLIF(TRIM(projectname), '')          AS project_name,
    workorderid::INTEGER                   AS work_order_id,
    workorderno::INTEGER                   AS work_order_no,
    attestuserid::INTEGER                  AS attest_user_id,
    costcenterid::INTEGER                  AS cost_center_id,
    totalrevenue::NUMERIC                  AS total_revenue,
    changeduserid::INTEGER                 AS changed_user_id,
    createduserid::INTEGER                 AS created_user_id,
    NULLIF(TRIM(workordername), '')        AS work_order_name,
    NULLIF(TRIM(attestfullname), '')       AS attest_full_name,
    NULLIF(TRIM(professioncode), '')       AS profession_code,
    employmenttypeid::INTEGER              AS employment_type_id,
    professionitemid::INTEGER              AS profession_item_id,
    travelondutycost::NUMERIC              AS travel_on_duty_cost,
    allowanceunitcost::NUMERIC             AS allowance_unit_cost,
    travelondutyprice::NUMERIC             AS travel_on_duty_price,
    travelprivatecost::NUMERIC             AS travel_private_cost,
    allowanceunitprice::NUMERIC            AS allowance_unit_price,
    NULLIF(TRIM(professionsalaryno), '')   AS profession_salary_no,
    NULLIF(TRIM(projectmanagername), '')   AS project_manager_name,
    NULLIF(TRIM(professionaccountno), '')::INTEGER   
                                           AS profession_account_no,
    dbt_scd_id,
    dbt_updated_at,
    dbt_valid_from,
    dbt_valid_to
FROM {{ ref('next_erp_booked_hours_snapshot') }}
WHERE dbt_valid_to IS NULL

