SELECT
    id::INTEGER                              AS id,
    NULLIF(created, '')::TIMESTAMP           AS created_at,
    createduserid::INTEGER                   AS created_user_id,
    NULLIF(changed, '')::TIMESTAMP           AS last_modified_at,
    changeduserid::INTEGER                   AS changed_user_id,
    NULLIF(TRIM(vouchernumber), '')          AS voucher_number,
    NULLIF(TRIM(text), '')                   AS text,
    projectid::INTEGER                       AS project_id,
    workorderid::INTEGER                     AS work_order_id,
    NULLIF(TRIM(accountno), '')::INTEGER     AS account_no,
    NULLIF(TRIM(invoicenumber), '')          AS invoice_number,
    invoiceable::BOOL                        AS is_invoiceable,
    NULLIF(ledgerdate, '')::TIMESTAMP        AS ledger_date,
    invoiceamount::NUMERIC                   AS invoice_amount,
    markup::NUMERIC                          AS markup,
    markupamount::NUMERIC                    AS markup_amount,
    revenuetransaction::BOOL                 AS is_revenue_transaction,
    NULLIF(TRIM(scannedurl), '')             AS scanned_url,
    NULLIF(TRIM(extvoucherid), '')           AS ext_voucher_id,
    NULLIF(TRIM(notes), '')                  AS notes,
    payoff::BOOL                             AS is_payoff,
    includeinreport::BOOL                    AS is_include_in_report,
    NULLIF(TRIM(transactiontype), '')        AS transaction_type,
    customerprice::NUMERIC                   AS customer_price,
    NULLIF(TRIM(projectno), '')::INTEGER     AS project_no,
    NULLIF(TRIM(projectname), '')            AS project_name,
    addition::BOOL                           AS is_addition,
    workorderno::INTEGER                     AS work_order_no,
    NULLIF(TRIM(workordername), '')          AS work_order_name,
    isrunningcost::BOOL                      AS is_running_cost,
    NULLIF(TRIM(accountdescription), '')     AS account_description,
    NULLIF(TRIM(accountgroup), '')           AS account_group,
    vatamount::NUMERIC                       AS vat_amount,
    invoiced::BOOL                           AS is_invoiced,
    locked::BOOL                             AS is_locked,
    chargesproductionbudget::BOOL            AS is_charges_production_budget,
    approvedbyproduction::BOOL               AS is_approved_by_production,
    awoamounttype1::NUMERIC                  AS awo_amount_type_1,
    awoamounttype2::NUMERIC                  AS awo_amount_type_2,
    awoamounttype3::NUMERIC                  AS awo_amount_type_3,
    workorderstatusid::INTEGER               AS work_order_status_id,
    workorderstatuscode::INTEGER             AS work_order_status_code,
    NULLIF(TRIM(workorderstatusname), '')    AS work_order_status_name,
    NULLIF(TRIM(workorderstatuscolor), '')   AS work_order_status_color,
    projectstatusid::INTEGER                 AS project_status_id,
    projectstatuscode::INTEGER               AS project_status_code,
    NULLIF(TRIM(projectstatusname), '')      AS project_status_name,
    NULLIF(TRIM(projectstatuscolor), '')     AS project_status_color,
    dbt_scd_id,
    dbt_updated_at,
    dbt_valid_from,
    dbt_valid_to
FROM {{ ref('next_erp_voucher_row_snapshot') }}
WHERE dbt_valid_to IS NULL

