SELECT
    id::INTEGER                              AS id,
    NULLIF(TRIM(description), '')            AS description,
    NULLIF(TRIM(codeno), '')                 AS code_no,
    NULLIF(changed, '')::TIMESTAMP           AS last_modified_at,
    NULLIF(TRIM(comment), '')                AS comment,
    NULLIF(created, '')::TIMESTAMP           AS created_at,
    addition::BOOL                           AS is_addition,
    costunit::NUMERIC                        AS cost_unit,
    islocked::BOOL                           AS is_locked,
    ispayoff::BOOL                           AS is_payoff,
    quantity::NUMERIC                        AS quantity,
    NULLIF(TRIM(accountno), '')::INTEGER     AS account_no,
    NULLIF(TRIM(invoicenumber), '')          AS invoice_number,
    priceunit::NUMERIC                       AS price_unit,
    totalcost::NUMERIC                       AS total_cost,
    chargeable::BOOL                         AS is_chargeable,
    isinvoiced::BOOL                         AS is_invoiced,
    itemunitid::INTEGER                      AS item_unit_id,
    totalprice::NUMERIC                      AS total_price,
    workorderid::INTEGER                     AS work_order_id,
    NULLIF(TRIM(itemunitname), '')           AS item_unit_name,
    showinmobile::BOOL                       AS is_show_in_mobile,
    tenderamount::NUMERIC                    AS tender_amount,
    usedquantity::NUMERIC                    AS used_quantity,
    bookedhoursid::INTEGER                   AS booked_hours_id,
    changeduserid::INTEGER                   AS changed_user_id,
    createduserid::INTEGER                   AS created_user_id,
    NULLIF(performeddate, '')::TIMESTAMP     AS performed_date,
    creditprojectid::INTEGER                 AS credit_project_id,
    performeduserid::INTEGER                 AS performed_user_id,
    plannedquantity::NUMERIC                 AS planned_quantity,
    articlecategoryid::INTEGER               AS article_category_id,
    NULLIF(TRIM(costunitpricelist), '')      AS cost_unit_price_list,
    NULLIF(TRIM(performedusername), '')      AS performed_user_name,
    NULLIF(TRIM(priceunitpricelist), '')     AS price_unit_price_list,
    NULLIF(TRIM(articlecategoryname), '')    AS article_category_name,
    NULLIF(TRIM(payoffunitpricelist), '')    AS payoff_unit_price_list,
    dbt_scd_id,
    dbt_updated_at,
    dbt_valid_from,
    dbt_valid_to
FROM {{ ref('next_erp_work_order_row_snapshot') }}
WHERE dbt_valid_to IS NULL

